{templateType Rector\Nette\Tests\Rector\Latte\RenameMethodLatteRector\Source\SomeTemplate}
-----
Array
(
    [0] => Rector\Nette\ValueObject\LatteVariableType Object
        (
            [name:Rector\Nette\ValueObject\LatteVariableType:private] => someClass
            [type:Rector\Nette\ValueObject\LatteVariableType:private] => Rector\Nette\Tests\Rector\Latte\RenameMethodLatteRector\Source\SomeClass
        )

    [1] => Rector\Nette\ValueObject\LatteVariableType Object
        (
            [name:Rector\Nette\ValueObject\LatteVariableType:private] => someText
            [type:Rector\Nette\ValueObject\LatteVariableType:private] => string
        )

)
