{templateType RectorNette\Tests\Rector\Latte\RenameMethodLatteRector\Source\SomeTemplate}

<div class="container"></div>
-----
Array
(
    [0] => RectorNette\ValueObject\LatteVariableType Object
        (
            [name:RectorNette\ValueObject\LatteVariableType:private] => someClass
            [type:RectorNette\ValueObject\LatteVariableType:private] => RectorNette\Tests\Rector\Latte\RenameMethodLatteRector\Source\SomeClass
        )

    [1] => RectorNette\ValueObject\LatteVariableType Object
        (
            [name:RectorNette\ValueObject\LatteVariableType:private] => someText
            [type:RectorNette\ValueObject\LatteVariableType:private] => string
        )

)
